 pipeline {
    agent any 

        stages {
            stage('Build Image') {
                steps {
                   script {
                        dockerapp = docker.build("leozin89/dist-api-node:${env.BUILD_ID}")
                }
            }
        }
    }
 }